FROM nciccbr/ccbr_ubuntu_24.04:v1

# build time variables
ARG BUILD_DATE="000000"
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_TAG="000000"
ENV BUILD_TAG=${BUILD_TAG}
ARG REPONAME="000000"
ENV REPONAME=${REPONAME}

ARG R_VERSION=4.4
ENV R_VERSION=${R_VERSION}

# install conda packages
RUN mamba install -y -c conda-forge \
    r-base=${R_VERSION} \
    r-argparse \
    r-amap \
    r-broom \
    r-cffr \
    r-colorspace \
    r-dendextend \
    r-devtools \
    r-dplyr \
    "r-ggplot2 <4.0.0" \
    r-ggrepel \
    r-gridExtra \
    r-here \
    r-matrix \
    r-mgcv \
    r-pak \
    r-patchwork \
    r-plotly \
    r-rcolorbrewer \
    r-readr \
    r-rmarkdown \
    r-survival \
    r-upsetr \
    r-viridis \
    bioconductor-annotationdbi \
    bioconductor-annotate \
    bioconductor-complexheatmap \
    bioconductor-delayedarray \
    bioconductor-deseq2 \
    bioconductor-edger \
    bioconductor-genomicranges \
    bioconductor-keggrest \
    bioconductor-limma \
    bioconductor-s4arrays \
    bioconductor-summarizedexperiment \
    bioconductor-sva \
  && conda clean -afy

# install dependencies, but not the R package itself
# using --mount avoids copying the context into the image
RUN --mount=type=bind,source=.,target=/opt2/MOSuite \
    R -e "pak::local_install_dev_deps('/opt2/MOSuite', upgrade=FALSE)" && \
    R -s -e "readr::write_csv(tibble::as_tibble(installed.packages()), '/data2/r-packages_mosuite-minimal.csv')"

# copy .Rprofile to R_HOME
ADD .github/.Rprofile /opt2/conda/lib/R/

# cleanup
WORKDIR /data2
RUN apt-get clean && apt-get purge \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
